name: Build and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Build Project
        run: yarn build

      - name: Linting
        run: yarn lint

      - name: Slack Notificatio
        run: yarn lint

  notify-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-lint
    steps:
      - name: Trigger Slack Notify Workflow
        uses: .github/workflows/slack-notify.yml