name: Slack Notification

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
  check_run:
    types: [rerequested, completed]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Slack message with build result
        if: failure() || success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
                "text": "Error in main branch.",
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}