name: Slack Notification

on:
  workflow_dispatch:

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
            "text": "Git push done in the repo , demogithubactionyttest"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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