name: Slack Notification

on:
  workflow_call:
  workflow_dispatch:

jobs:
  send-slack-message:
    runs-on: ubuntu-latest

    steps:
      - name: Slack message with build result
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload-file-path: "./.github/resources/payload-slack-content.json"
          payload-file-path-parsed: false
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}